# Generated by Django 5.0 on 2024-09-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_count', models.IntegerField()),
                ('out_count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
