
# Generated by Django 5.0 on 2024-10-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
